version: "3.7"

services:
  app:
    image: kangana512/demodeploy:latest
    ports:
      - "4555:3000"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    environment:
      TESTENV: testenv
    networks:
      - webnet
    deploy:
      placement:
        constraints:
          - node.role == manager
networks:
  webnet:
    driver: overlay
    attachable: true
