name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Check out code into the go module dir
        uses: actions/checkout@v2

      - name: Test
        run: go test -v ./...

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kangana512/demodeploy:latest

      - name: deploy to portainer
        uses: LGinC/portainer-stack-deploy@master
        with:
          serverurl: http://103.253.72.230:9000
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}
          endpointId: 1
          stackname: demodeploy
          imagename: kangana512/demodeploy:latest
          docker_compose: |
            version: "3.7"

            services:
              app:
                image: kangana512/demodeploy:latest
                ports:
                  - "4555:3000"
                deploy:
                  replicas: 3
                  restart_policy:
                    condition: on-failure
                environment:
                  TESTENV: testenv
                networks:
                  - webnet
                deploy:
                  placement:
                    constraints:
                      - node.role == manager
            networks:
              webnet:
                driver: overlay
                attachable: true
