name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Check out code into the go module dir
        uses: actions/checkout@v2

      - name: Test
        run: go test -v ./...

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kangana512/demodeploy:latest

      # - name: Deploy to swarm
      #   uses: sagebind/docker-swarm-deploy-action@v2
      #   with:
      #     remote_host: ssh://root@103.253.72.230
      #     ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
      #     ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
      #     args: stack deploy --compose-file stack.yaml coolapp