name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Check out code into the go module dir
        uses: actions/checkout@v2

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -v ./...
